myFootballSite/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictor.urls'))
]

predictor/urls.py
from django.urls import path
from . import views

app_name = 'predictor'

urlpatterns = [
    path('predictions/', views.predictions, name='predictions'),
    path('dataVisualization/', views.dataVisualization, name='dataVisualization'),
    path('predictionResults/', views.predictionResults, name='predictionResults'),
    path('',views.homePage, name='homePage')
]

predictor/models.py
from cProfile import label
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Predictions(models.Model):
    
    Team_One = models.CharField(max_length=50)
    Team_One_Passing_Yards = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Rushing_Yards = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Passing_Yards_Allowed_On_Defense = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Rushing_Yards_Allowed_On_Defense = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Turnovers_Created = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Third_Downs_Converted = models.FloatField(validators=[MinValueValidator(0)])
    Team_One_Sacks = models.FloatField(validators=[MinValueValidator(0)])

    Team_Two = models.CharField(max_length=50)
    Team_Two_Passing_Yards = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Rushing_Yards = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Passing_Yards_Allowed_On_Defense = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Rushing_Yards_Allowed_On_Defense = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Turnovers_Created = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Third_Downs_Converted = models.FloatField(validators=[MinValueValidator(0)])
    Team_Two_Sacks = models.FloatField(validators=[MinValueValidator(0)])

predictor/forms.py
from django import forms
from .models import Predictions
from django.forms import ModelForm


class PredictionsForm(ModelForm):
    class Meta:
        model = Predictions
        # fields = ['passingYards', 'rushingYards', 'passingYardsAllowedDefense', 'rushingYardsAllowedDefense', 'turnoversCreated', 'thirdDownsConverted', 'sacks']
        fields = '__all__' #  pass in all model fields as form fields

predictor/views.py
from re import template
from django.urls import reverse
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from .ANN import annML

from .models import models
# from ... import ANN
# from myFootballSite import predictor
from .forms import PredictionsForm
# Create your views here.
def predictions(request):

    #Post request --> form contents --> 
    if request.method == 'POST':
        
        form = PredictionsForm(request.POST)
        if form.is_valid():
            form.save()
            form = form.cleaned_data
            return render(request, 'predictor/predictionResults.html', context = form)

    else:
      form = PredictionsForm()
    return render(request, 'predictor/predictions.html', context={'form':form})

def dataVisualization(request):
    return render(request, 'predictor/dataVisualization.html')

def predictionResults(request):

    print('success')
    if request.method == 'POST':
        post_data = request.POST

        print(post_data)
        team_one = []
        team_two = []

        for key, value in post_data.items():
            # print(key, "===>", value)
            if "One" in str(key):
                if value != post_data.get('Team_One'):
                    team_one.append(float(value))
            elif"Two" in str(key):
                if value != post_data.get('Team_Two'):
                    team_two.append(float(value))

        print("Team ONe => ", team_one, "\n","Team Two => ", team_two)
 


    team1_win_percentage = float(annML(team_one))
    team2_win_percentage = float(annML(team_two))

    print(team1_win_percentage)

    data = {
        'Team_One': post_data.get('Team_One'),
        'Team_One_Win_Percentage': team1_win_percentage,
        'Team_Two': post_data.get('Team_Two'),
        'Team_two_Win_Percentage': team2_win_percentage
    }
    return render(request, 'predictor/predictionResults.html', context=data) 


def homePage(request):
    return render (request, 'predictor/homePage.html')

predictor/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'predictor/custom.css' %}">

</head>
<body id="bg" class='img-fluid' style="background-image: url('{% static "predictor/images/footballFieldNight.jpg"%}')">
    {% include 'navbar.html' %}

{% block content%}{% endblock content%}
</body>
</html>

predictor/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <img src="{% static 'predictor/images/Football.png' %}" alt="" width="30" height="24">
          <a class="navbar-brand" href='/'>Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/predictions/">Predictions</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/dataVisualization/">DataVisualization</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Coming Soon</a>
              </li>
            </ul>
            <img src="{% static 'predictor/images/Football.png' %}" alt="" width="30" height="24">
          </div>
        </div>
      </nav>

predictor/templates/predictor/dataVisualization.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'predictor/custom.css' %}">
{% block content%}


<h1 id = 'myheaders' >Data Visualization Page</h1>
{% comment %} <img src="{% static 'predictor/images/Points Scored x Total Yards.jpg' %}" class="img-fluid" alt="Points Scored x Total Yards">
<img src="{% static 'predictor/images/predictionAccuracyPiechart.jpg' %}" class="img-fluid" alt="predictionAccuracyPiechart">
<img src="{% static 'predictor/images/violinplot.jpg' %}" class="img-fluid" alt="violinplot">

<div class="row">
    <div class="column">
      <img src="{% static 'predictor/images/Points Scored x Total Yards.jpg' %}" alt="Points Scored x Total Yards" style="width:30%">
    </div>
    <div class="column">
      <img src="{% static 'predictor/images/predictionAccuracyPiechart.jpg' %}" alt="predictionAccuracyPiechart" style="width:30%">
    </div>
    <div class="column">
      <img src="{% static 'predictor/images/violinplot.jpg' %}" alt="violinplot" style="width:30%">
    </div>
  </div> {% endcomment %}

  <div class="row">
    <div class="col-sm-4">
        <img src="{% static 'predictor/images/Points Scored x Total Yards.jpg' %}" class="img-fluid" alt="Points Scored x Total Yards">
    </div>    
        <div class="col-sm-4">
            <img src="{% static 'predictor/images/predictionAccuracyPiechart.jpg' %}" class="img-fluid" alt="predictionAccuracyPiechart">
        </div>
    <div class="col-sm-4">
        <img src="{% static 'predictor/images/violinplot.jpg' %}" class="img-fluid" alt="violinplot">
    </div>
  </div>
{% endblock content%}

predictor/templates/predictor/homePage.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
<h1 id = 'myheaders' >NFL Predictions Site</h1>

{% endblock content%}

predictor/templates/predictor/predictionResults.html
{% extends 'base.html' %}


{% block content%}


  <h1 id = 'myheaders'>Predictions Results</h1>
  <p text align = center>Team one :{{Team_One}}</p>
  <p text align = center>Team one win percentage is: {{Team_One_Win_Percentage}}</p>
  <p text align = center>Team two :{{Team_Two}}</p>
  <p text align = center>Team two win percentage is: {{Team_two_Win_Percentage}}</p>

  </div>


{% endblock content%}

predictor/templates/predictor/predictions.html
{% extends 'base.html' %}

{% block content%}


    <h1 id ='myheaders'> Predictions Page</h1>
    <div  align = center id = 'myform' class = 'container myform'>
        <form action = {% url 'predictor:predictionResults' %} method = 'POST'>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>

    </div>

{% endblock content%}